// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwgnmypbqqdhqrghaizo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3Z25teXBicXFkaHFyZ2hhaXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjA4NTAsImV4cCI6MjA2NTMzNjg1MH0.eHyJ8NIpAwvVqoYhiPptHUhmVNo6ZCFCq8Oc4GAOJ88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);